#!/bin/bash

# define the path to the buildroot
OPENWRT_BUILDROOT="/home/rajiv/OpenWRT-Buildroot/openwrt"

# define the relative paths
STAGING_DIR_RELATIVE="staging_dir"
TOOLCHAIN_RELATIVE="$STAGING_DIR_RELATIVE/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2"
TARGET_RELATIVE="$STAGING_DIR_RELATIVE/target-mips_34kc_uClibc-0.9.33.2"

# define the toolchain paths 
TOOLCHAIN="$OPENWRT_BUILDROOT/TOOLCHAIN_RELATIVE"
TOOLCHAIN_BIN="$OPENWRT_BUILDROOT/$TOOLCHAIN_RELATIVE/bin"

TOOLCHAIN_INCLUDE="$OPENWRT_BUILDROOT/$TOOLCHAIN_RELATIVE/include"
TOOLCHAIN_LIB="$OPENWRT_BUILDROOT/$TOOLCHAIN_RELATIVE/lib"
TOOLCHAIN_USR_INCLUDE="$OPENWRT_BUILDROOT/$TOOLCHAIN_RELATIVE/usr/include"
TOOLCHAIN_USR_LIB="$OPENWRT_BUILDROOT/$TOOLCHAIN_RELATIVE/usr/lib"

# define the target paths
TARGET="$OPENWRT_BUILDROOT/TARGET_RELATIVE"
TARGET_INCLUDE="$OPENWRT_BUILDROOT/$TARGET_RELATIVE/include"
TARGET_LIB="$OPENWRT_BUILDROOT/$TARGET_RELATIVE/lib"
TARGET_USR_INCLUDE="$OPENWRT_BUILDROOT/$TARGET_RELATIVE/usr/include"
TARGET_USR_LIB="$OPENWRT_BUILDROOT/$TARGET_RELATIVE/usr/lib"

export STAGING_DIR="OPENWRT_BUILDROOT/$STAGING_DIR_RELATIVE"

# define the compilers and such
TOOLCHAIN_CC="$TOOLCHAIN_BIN/mips-openwrt-linux-gcc"
TOOLCHAIN_CXX="$TOOLCHAIN_BIN/mips-openwrt-linux-g++"
TOOLCHAIN_LD="$TOOLCHAIN_BIN/mips-openwrt-linux-ld"

TOOLCHAIN_AR="$TOOLCHAIN_BIN/mips-openwrt-linux-ar"
TOOLCHAIN_RANLIB="$TOOLCHAIN_BIN/mips-openwrt-linux-ranlib"

# define the FLAGS
INCLUDE_LINES="-I $TOOLCHAIN_USR_INCLUDE -I $TOOLCHAIN_INCLUDE -I $TARGET_USR_INCLUDE -I $TARGET_INCLUDE"
TOOLCHAIN_CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -fpic"
TOOLCHAIN_CFLAGS="$TOOLCHAIN_CFLAGS $INCLUDE_LINES"

TOOLCHAIN_CXXFLAGS="" # LAZAR: figure this out!
TOOLCHAIN_CXXFLAGS="$TOOLCHAIN_CXXFLAGS $INCLUDE_LINES"

TOOLCHAIN_LDFLAGS="-L$TOOLCHAIN_USR_LIB -L$TOOLCHAIN_LIB -L$TARGET_USR_LIB -L$TARGET_LIB"


echo "CC=$TOOLCHAIN_CC"
echo "CXX=$TOOLCHAIN_CXX"
echo "LD=$TOOLCHAIN_LD"
echo "CFLAGS=$TOOLCHAIN_CFLAGS"
echo "LDFLAGS=$TOOLCHAIN_LDFLAGS"
echo ""


# first run make clean
make clean 

# run the make command
make\
    CC="$TOOLCHAIN_CC" \
    CXX="$TOOLCHAIN_CXX" \
    LD="$TOOLCHAIN_LD" \
    CFLAGS="$TOOLCHAIN_CFLAGS" \
    LDFLAGS="$TOOLCHAIN_LDFLAGS"
